version: '3.9'

services:
  backend:
    build:
      context: ./Backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - webnet
    restart: always
    env_file:
      - ./Backend/.env

  nginx:
    build:
      context: ./Nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webnet
    restart: always

networks:
  webnet:
    driver: bridge